# Generated by Django 6.0.3 on 2026-03-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_text',
            new_name='home_text',
        ),
    ]
