# Generated by Django 6.0.3 on 2026-04-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footerlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='email',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='scholar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
