# Generated by Django 6.0.3 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projectpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='intro',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
