# Generated by Django 6.0.3 on 2026-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_projectindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='intro',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
