# Generated by Django 6.0.3 on 2026-04-11 04:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_projectpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='tools',
            field=wagtail.fields.StreamField([('tool', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Tool'})}, help_text='Add a list of strings'),
        ),
    ]
